### PR TITLE
Atomicity for Timers

### PR DESCRIPTION
**Pull request by nickiaconis**
Create atomicity macro and use it to guarantee Timer1/2 16bit register reads/writes are atomic.

Also, add a gitignore.

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Can you explain what this change does and why it is necessary? 

I'm looking at the functions that manipulate the 16-bit registers in the official Arduino core, and it doesn't look like they've taken any measures like this when writing to the 16-bit registers.

Thanks - I just don't want to merge something without understanding the ramifications of the change,.

**Comment by nickiaconis** [comment]
Totally understandable. I should have provided more info in my initial post.

Section 12.11 of the ATtinyX41 datasheet (pp. 108–111) explains:

> TCNTn, OCRnA/B, and ICRn are 16-bit registers that ... must be byte accessed using two read or write operations. Each 16-bit timer has a single 8-bit register for temporary storing of the high byte of the 16-bit access. The same temporary register is shared between all 16-bit registers within each 16-bit timer... When the low byte ... is written ... the high byte stored in the temporary register and the low byte written are both copied into the 16-bit register... When the low byte ... is read ... the high byte of the 16-bit register is copied into the temporary register...
> To do a 16-bit write, the high byte must be written before the low byte. For a 16-bit read, the low byte must be read before the high byte.

There is a code example showing that a write in C translates to two consecutive **`out`** operations in assembly, and a read translates to two consecutive **`in`** operations. It further explains:

> It is important to notice that accessing 16-bit registers are atomic operations. If an interrupt occurs between the two instructions accessing the 16-bit register, and the interrupt code updates the temporary register by accessing the same or any other of the 16-bit timer registers, then the result of the access outside the interrupt will be corrupted. Therefore, when both the main code and the interrupt code update the temporary register, the main code must disable the interrupts during the 16-bit access.

Then there are two code samples, one for reading and one for writing the 16-bit registers atomically, both of which are nearly identical to the atomic access found in `WInterrupts.c`.

Since we can't know what the end-user of the core is implementing, it would make sense to code these accesses defensively by making them atomic operations.

**Comment by SpenceKonde** [comment]
I hope this wasn't a mistake.

**Comment by nickiaconis** [comment]
Coincidentally, upon googling "avr cli" to better understand the code block from `WInterrupts.c`, I came across this post which specifically mentions reading/writing TCNT1 as a use case for `cli()`: http://www.avrfreaks.net/comment/342616#comment-342616

**Pull request merged**
