### PR TITLE
Added 14.7456MHz clock.

### PR DESCRIPTION
**Pull request by AlexSatrapa**
As per http://forum.arduino.cc/index.php?topic=333064.msg2373285#msg2373285

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Thanks - I've been working on adding the UART clocks as well (two entries were added, but not one for 14.7456 yet), though I hadn't started adding them to boards.txt yet. 

But there's another step - delayMicroseconds() won't work at that speed; the times will be way off (as it will fall through to the 12mhz part) 

You need to also add, in wiring.c, ( https://github.com/SpenceKonde/arduino-tiny-841/blob/master/avr/cores/tiny/wiring.c ) another #ifdef block, like the ones on lines 155 to 295 there - you can see that I recently added entries for the 9.216 and 11.-whatever UART clock. delayMicroseconds(). It doesn't have to be perfect (with these weird baud rates, that's not practical), just "close enough", since people can use timers if they need exact delays.

**Comment by AlexSatrapa** [comment]
I'll have a look at that and hopefully have something for you Saturday!

How would I go about tuning this? Just use micros() to time a loop that toggles an output and monitor that on an oscilloscope? I could sync it with a PWM output too I guess?

Where do I start looking for adjusting UART clocks?

**Comment by SpenceKonde** [comment]
You know exactly what you want the ratio to be, since the loop takes 4 clock cycles. They manipulate the us variable to turn it into the right number of times the loop needs to run. You need to multiply it by ~3.68 (without using floating point multiplication). 
There's not really any testing involved other than a sanity check - you just need to do it as fast as possible, because at the bottom where it corrects for the number of us used in the code above, you're constrained by the lowest possible number that could be passed to it (since you need to avoid it overflowing) after those manipulations (I just realized I'd slipped up here and committed a fix for it for 9.2 and 11.x).

**Comment by AlexSatrapa** [comment]
I need some help on the maths. With a clock speed of 14.7456Mhz, I have a cycle period of about 0.0678µs. Thus for a 4 cycle loop we're looking at about 0.2712µs, meaning the loop has to be run about 3.6873 times.

I think my main question is whether  us >> 3 takes one cycle or three. I've added my working into the comments in wiring.c.

**Comment by AlexSatrapa** [comment]
And I've broken the commit history somehow, with your commit included in mine.

**Comment by SpenceKonde** [comment]
That looks good to me.

**Pull request merged**
